import { defineArrayMember, defineField, defineType } from "sanity";

export const artistType = defineType({
  name: "artist",
  title: "Artista",
  type: "document",
  fields: [
    defineField({ name: "name", title: "Nombre", type: "string", validation: (rule) => rule.required() }),
    defineField({ name: "slug", title: "Slug", type: "slug", options: { source: "name", maxLength: 96 }, validation: (rule) => rule.required() }),
    defineField({ name: "status", title: "Estado", type: "string", options: { list: [{ title: "Publicado", value: "published" }, { title: "Oculto", value: "hidden" }, { title: "Archivo", value: "archived" }], layout: "radio" }, initialValue: "hidden", validation: (rule) => rule.required() }),
    defineField({ name: "artistKind", title: "Tipo de entidad", type: "string", options: { list: [{ title: "Persona", value: "person" }, { title: "Grupo musical", value: "musicGroup" }, { title: "Otro formato", value: "other" }], layout: "radio" }, description: "Se utiliza para generar datos estructurados correctos." }),
    defineField({ name: "relationshipType", title: "Relación con la agencia", type: "array", of: [defineArrayMember({ type: "string" })], options: { list: ["Management", "Booking", "Colaboración"] } }),
    defineField({ name: "shortDescription", title: "Descripción corta", type: "text", rows: 3, validation: (rule) => rule.max(240) }),
    defineField({ name: "biography", title: "Biografía", type: "array", of: [defineArrayMember({ type: "block" })] }),
    defineField({
      name: "mainImage",
      title: "Imagen principal",
      type: "image",
      options: { hotspot: true },
      fields: [defineField({ name: "alt", title: "Texto alternativo", type: "string", validation: (rule) => rule.custom((value, context) => context.parent && !value ? "El texto alternativo es obligatorio." : true) })],
    }),
    defineField({ name: "gallery", title: "Galería", type: "array", of: [defineArrayMember({ type: "image", options: { hotspot: true }, fields: [defineField({ name: "alt", title: "Texto alternativo", type: "string" })] })] }),
    defineField({ name: "artistCategories", title: "Categorías", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "artistCategory" }] })] }),
    defineField({ name: "musicGenres", title: "Estilos musicales", type: "array", of: [defineArrayMember({ type: "string" })], options: { layout: "tags" } }),
    defineField({ name: "eventTypes", title: "Tipos de evento", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "eventType" }] })] }),
    defineField({ name: "availableFormats", title: "Formatos disponibles", type: "array", of: [defineArrayMember({ type: "string" })], options: { layout: "tags" } }),
    defineField({ name: "languages", title: "Idiomas", type: "array", of: [defineArrayMember({ type: "string" })], options: { layout: "tags" } }),
    defineField({ name: "territory", title: "Ámbito geográfico", type: "string" }),
    defineField({ name: "videoUrl", title: "Vídeo principal", type: "url" }),
    defineField({ name: "secondaryVideos", title: "Vídeos adicionales", type: "array", of: [defineArrayMember({ type: "url" })] }),
    defineField({ name: "spotifyUrl", title: "Spotify", type: "url" }),
    defineField({ name: "socialLinks", title: "Redes sociales", type: "array", of: [defineArrayMember({ type: "navigationItem" })] }),
    defineField({ name: "pressKit", title: "Dossier de prensa", type: "file", options: { accept: ".pdf" } }),
    defineField({ name: "technicalRider", title: "Rider técnico", type: "file", options: { accept: ".pdf" } }),
    defineField({ name: "featured", title: "Destacado", type: "boolean", initialValue: false }),
    defineField({ name: "featuredOrder", title: "Orden destacado", type: "number", validation: (rule) => rule.integer().min(0) }),
    defineField({ name: "hotelSuitable", title: "Adecuado para hoteles", type: "boolean", initialValue: false }),
    defineField({ name: "weddingSuitable", title: "Adecuado para bodas", type: "boolean", initialValue: false }),
    defineField({ name: "corporateSuitable", title: "Adecuado para corporativo", type: "boolean", initialValue: false }),
    defineField({ name: "relatedArtists", title: "Artistas relacionados", type: "array", of: [defineArrayMember({ type: "reference", to: [{ type: "artist" }] })] }),
    defineField({ name: "seoTitle", title: "Título SEO", type: "string", validation: (rule) => rule.max(60) }),
    defineField({ name: "seoDescription", title: "Descripción SEO", type: "text", rows: 3, validation: (rule) => rule.max(160) }),
    defineField({ name: "shareImage", title: "Imagen social", type: "image", options: { hotspot: true } }),
    defineField({ name: "publishedAt", title: "Fecha de publicación", type: "datetime" }),
  ],
  preview: {
    select: { title: "name", media: "mainImage", status: "status", relationship: "relationshipType.0" },
    prepare({ title, media, status, relationship }) {
      return { title, media, subtitle: [relationship, status === "published" ? "Publicado" : "No publicado"].filter(Boolean).join(" · ") };
    },
  },
});
